---
# tasks file for aaa

- name: Install required system packages
  apt:
    name:
      - acct
      - sudo
    state: present
    update_cache: yes
    cache_valid_time: 86400

- name: Ensure empty sudo group
  lineinfile:
    path: "/etc/group"
    regexp: "^sudo:x:27:.+"
    line: "sudo:x:27:"

- name: Disable root SSH direct access
  lineinfile:
    path: /etc/ssh/sshd_config
    # Se estiver com 'yes' substitui por 'without-password'
    regexp: "^PermitRootLogin\\s+yes"
    line: "PermitRootLogin without-password"
  notify:
    - Restart sshd

- name: Restrict SSH user groups
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^AllowGroups"
    line: "AllowGroups {{ cmc_aaa_ssh_user_groups }}" # type: space separated LDAP groups string
  notify:
    - Restart sshd

- name: Create users home directory
  lineinfile:
    path: /etc/pam.d/common-session
    state: present
    insertbefore: "pam_unix\\.so"
    line: "session required pam_mkhomedir.so skel=/etc/skel/ umask=0022"

- name: Configure sudo
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/cmc
    owner: root
    group: root
    mode: "0440"
