---
# tasks file for ansible-cmc-servers
- name: Set hostname
  hostname:
    name: "{{ cmc_server_hostname | mandatory }}" # type: string

- name: Configure email alias from root to admin
  lineinfile:
    path: "/etc/aliases"
    regexp: '^root: suporte'
    line: 'root: admin'

- name: Configure mail domain
  lineinfile:
    path: /etc/mailname
    state: present
    line: "cmc.pr.gov.br"

- name: Configure resolv.conf domain
  lineinfile:
    path: /etc/resolv.conf
    state: present
    line: "domain cmc.pr.gov.br"

- name: Configure resolv.conf domain search
  lineinfile:
    path: /etc/resolv.conf
    state: present
    line: "search cmc.pr.gov.br"

- name: Ensure template IP and name are removed from hosts file
  lineinfile:
    path: /etc/hosts
    state: absent
    regexp: "{{ cmc_template_ip }}"  # type: regex string
  when: cmc_template_ip is defined

- name: Ensure hosts is right
  lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ ansible_default_ipv4.address }} {{ cmc_server_hostname }}.cmc.pr.gov.br {{ cmc_server_hostname }}"

- name: Install required system packages
  apt:
    name:
      - ufw
      - rsync
      - ntp
      - sudo
      - unattended-upgrades
      - software-properties-common
      - curl
      - vim
      - ncdu
      - iftop
      - nload
    state: latest
    update_cache: yes

- name: Allow SSH on Firewall
  ufw:
    rule: allow
    name: SSH
    src: "{{ cmc_dtic_network | mandatory }}" # type: IPv4 address block

- name: Allow SSH from VPN
  ufw:
    rule: allow
    name: SSH
    src: "{{ cmc_dtic_vpn_network }}" # type: IPv4 address block
  when: cmc_dtic_vpn_network is defined

- name: Configure default Firewall rule
  ufw:
    state: enabled
    default: reject
    direction: incoming

- name: Configure NTP
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  # when: cmc_ntp_servers is defined # type: IPv4 address list
  notify:
    - restart ntp

- name: Configure unattended-upgrades
  lineinfile:
    path: "/etc/apt/apt.conf.d/50unattended-upgrades"
    regexp: '^//Unattended-Upgrade::MinimalSteps'
    line: 'Unattended-Upgrade::MinimalSteps "true";'

- name: Configure unattended-upgrades
  lineinfile:
    path: "/etc/apt/apt.conf.d/50unattended-upgrades"
    regexp: '^//Unattended-Upgrade::Mail\b'
    line: 'Unattended-Upgrade::Mail "root";'

- name: Configure bash aliases commands
  copy:
    src: cmc-aliases.sh
    dest: /etc/profile.d/cmc-aliases.sh
    mode: 0644

- name: Configure command history
  lineinfile:
    path: /etc/bash.bashrc
    state: present
    line: "export HISTTIMEFORMAT=\"%F %T \""
