---
# tasks file for ansible-cmc-servers
- include: mail.yml
  when: cmc_configure_mail == true

- name: Set hostname
  hostname:
    name: "{{ cmc_server_hostname | mandatory }}" # type: string

- name: Configure resolv.conf domain
  lineinfile:
    path: /etc/resolv.conf
    state: present
    line: "domain cmc.pr.gov.br"

- name: Configure resolv.conf domain search
  lineinfile:
    path: /etc/resolv.conf
    state: present
    line: "search cmc.pr.gov.br"

- name: Ensure template IP and name are removed from hosts file
  lineinfile:
    path: /etc/hosts
    state: absent
    regexp: "{{ cmc_template_ip }}" # type: regex string
  when: cmc_template_ip is defined

- name: Ensure hosts is right
  lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ ansible_default_ipv4.address }} {{ cmc_server_hostname }}.cmc.pr.gov.br {{ cmc_server_hostname }}"

- name: Install required system packages
  apt:
    name:
      - acct
      - curl
      - iftop
      - gpg
      - ncdu
      - nload
      - ntp
      - parted
      - rsync
      - software-properties-common
      - sudo
      - ufw
      - unattended-upgrades
      - vim
    state: latest
    update_cache: yes
    cache_valid_time: 86400

- name: Ensure empty sudo group
  lineinfile:
    path: "/etc/group"
    regexp: "^sudo:x:27:.+"
    line: "sudo:x:27:"

- include: ldap.yml
  when: cmc_configure_ldap == true

- include: docker.yml
  when: cmc_install_docker == true

- name: Allow SSH on Firewall
  ufw:
    rule: allow
    name: SSH
    src: "{{ cmc_dtic_network | mandatory }}" # type: IPv4 address block

- name: Allow SSH from VPN
  ufw:
    rule: allow
    name: SSH
    src: "{{ cmc_dtic_vpn_network }}" # type: IPv4 address block
  when: cmc_dtic_vpn_network is defined

- name: Configure default Firewall rule
  ufw:
    state: enabled
    default: reject
    direction: incoming

- name: Configure NTP
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: "0644"
    backup: yes
  # when: cmc_ntp_servers is defined # type: FQDN and IPv4 address list
  notify:
    - restart ntp

- name: Configure unattended-upgrades steps
  lineinfile:
    path: "/etc/apt/apt.conf.d/50unattended-upgrades"
    regexp: "^//Unattended-Upgrade::MinimalSteps"
    line: 'Unattended-Upgrade::MinimalSteps "true";'

- name: Configure unattended-upgrades mail
  lineinfile:
    path: "/etc/apt/apt.conf.d/50unattended-upgrades"
    regexp: "^//Unattended-Upgrade::Mail\b"
    line: 'Unattended-Upgrade::Mail "root";'

- name: Configure bash aliases commands
  copy:
    src: cmc-aliases.sh
    dest: /etc/profile.d/cmc-aliases.sh
    owner: root
    group: root
    mode: "0644"

- name: Configure command history
  lineinfile:
    path: /etc/bash.bashrc
    state: present
    line: 'export HISTTIMEFORMAT="%F %T "'
