---
# handlers file for ansible-cmc-servers
- name: restart ntp
  service:
    name: ntp
    state: restarted

- name: restart nslcd
  service:
    name: nslcd
    state: restarted

- name: restart ssh
  service:
    name: sshd
    state: restarted
