---
# tasks file for servers
- include: mail.yml
  when: cmc_smtp_server is defined

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname_short | mandatory }}" # type: string

- name: Configure resolv.conf domain
  lineinfile:
    path: /etc/resolv.conf
    state: present
    line: "domain cmc.pr.gov.br"

- name: Configure resolv.conf domain search
  lineinfile:
    path: /etc/resolv.conf
    state: present
    line: "search cmc.pr.gov.br"

- name: Ensure template IP and name are removed from hosts file
  lineinfile:
    path: /etc/hosts
    state: absent
    regexp: "{{ cmc_template_ip }}" # type: regex string
  when: cmc_template_ip is defined

- name: Ensure localhost in hosts is right
  lineinfile:
    path: /etc/hosts
    state: present
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1	{{ inventory_hostname_short }}.cmc.pr.gov.br {{ inventory_hostname_short }}"

- name: Ensure hostname in hosts is right
  lineinfile:
    path: /etc/hosts
    state: present
    regexp: '^{{ ansible_default_ipv4.address }}'
    line: "{{ ansible_default_ipv4.address }}	{{ inventory_hostname_short }}.cmc.pr.gov.br {{ inventory_hostname_short }}"

- name: Install required system packages
  apt:
    name:
      - acct
      - curl
      - iftop
      - gpg
      - ncdu
      - nload
      - ntp
      - parted
      - rsync
      - software-properties-common
      - ufw
      - unattended-upgrades
      - vim
    state: latest
    update_cache: yes
    cache_valid_time: 86400

- include: docker.yml
  when: cmc_install_docker == true

- name: Ensure SSH for local user
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^AllowGroups +(?!suporte)"
    line: "AllowGroups suporte" # type: space separated LDAP groups string
  when: cmc_ldap_server is not defined
  notify:
    - restart ssh

- name: Disable root SSH access
  lineinfile:
    path: /etc/ssh/sshd_config
    # lookahead para substituir qualquer coisa diferente de 'no'
    regexp: "^PermitRootLogin +(?!no)"
    line: "PermitRootLogin no"
  notify:
    - restart ssh

- name: Allow SSH on Firewall
  ufw:
    rule: allow
    name: SSH
    src: "{{ cmc_dtic_network | mandatory }}" # type: IPv4 address block

- name: Allow SSH from VPN
  ufw:
    rule: allow
    name: SSH
    src: "{{ cmc_dtic_vpn_network }}" # type: IPv4 address block
  when: cmc_dtic_vpn_network is defined

- name: Configure default Firewall rule
  ufw:
    state: enabled
    default: reject
    direction: incoming

- name: Configure NTP
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: "0644"
    backup: yes
  # when: cmc_ntp_servers is defined # type: FQDN and IPv4 address list
  notify:
    - restart ntp

- name: Configure unattended-upgrades steps
  lineinfile:
    path: "/etc/apt/apt.conf.d/50unattended-upgrades"
    regexp: "^//Unattended-Upgrade::MinimalSteps"
    line: 'Unattended-Upgrade::MinimalSteps "true";'

- name: Configure unattended-upgrades mail
  lineinfile:
    path: "/etc/apt/apt.conf.d/50unattended-upgrades"
    regexp: "^//Unattended-Upgrade::Mail\b"
    line: 'Unattended-Upgrade::Mail "root";'

- name: Configure bash aliases commands
  copy:
    src: cmc-aliases.sh
    dest: /etc/profile.d/cmc-aliases.sh
    owner: root
    group: root
    mode: "0644"

- name: Configure command history
  lineinfile:
    path: /etc/bash.bashrc
    state: present
    line: 'export HISTTIMEFORMAT="%F %T "'
