---
- name: Allow SSH agent forwarding
  lineinfile:
    path: /etc/ssh/sshd_config
    # lookahead para substituir qualquer coisa diferente de 'no'
    regexp: "^AllowAgentForwarding\\s+(?!no)"
    line: "AllowAgentForwarding {{ cmc_enable_ssh_agent }}"
  when: cmc_enable_ssh_agent is defined
  notify:
    - Restart sshd

- name: Allow SSH on Firewall
  ufw:
    rule: allow
    name: SSH
    src: "{{ cmc_dtic_network | mandatory }}" # type: IPv4 address block

- name: Allow SSH from VPN
  ufw:
    rule: allow
    name: SSH
    src: "{{ cmc_dtic_vpn_network }}" # type: IPv4 address block
  when: cmc_dtic_vpn_network is defined
